### ISSUE TITLE
RNNのKerasサンプルコードについて

### ISSUE THREAD

**Issue by guntama** [yusugomori/deeplearning-tensorflow-keras#2]
5章のRNNのKerasコードは時系列データを扱うためにmodel.fit()にshuffle=Falseが必要ではないですか?

**Comment by yusugomori** [comment]
ありがとうございます、実社会の時系列データ（例えば株価等）ではご質問のとおりシャッフルしてはならないケースがほとんどです。こちらで扱っているのは周期性があると事前に分かっているトイプロブレムなので、シャッフルしてしまっています。
次版ではそのへんも言及したほうが良いかもしれませんね。ありがとうございます！
